/** Domain model for Umvix PostPilot. Mirrors the Supabase schema. */

export type Role = "admin" | "employee";

export type LogStatus = "pending" | "posted" | "missed" | "skipped";

export type NotificationType = "midday_reminder" | "eod_missed" | "admin_digest";

/**
 * Posting schedule attached to an assignment.
 * Days use ISO numbering: 1 = Monday … 7 = Sunday.
 * `weekly_quota` is a documented v2 shape — not generated by the UI yet.
 */
export type Schedule =
  | { type: "daily" }
  | { type: "weekdays"; days: number[] }
  | { type: "weekly_quota"; count: number };

export type NotificationPrefs = {
  /** Override of the org-wide reminder time, "HH:mm". */
  reminder_time?: string;
  midday_enabled?: boolean;
  eod_enabled?: boolean;
};

export type Organization = {
  id: string;
  name: string;
  default_timezone: string;
  eod_cutoff_time: string; // "HH:mm:ss" from Postgres time
  reminder_time: string;
  late_counts_for_streaks: boolean;
  send_positive_digest: boolean;
  allow_notification_optout: boolean;
  created_at: string;
};

export type Profile = {
  id: string;
  org_id: string;
  role: Role;
  full_name: string;
  avatar_url: string | null;
  timezone: string;
  is_active: boolean;
  notification_prefs: NotificationPrefs;
  created_at: string;
};

export type Platform = {
  id: string;
  org_id: string;
  name: string;
  description: string;
  logo_url: string | null;
  brand_color: string;
  url_template: string | null;
  sort_order: number;
  is_active: boolean;
  archived_at: string | null;
  created_by: string | null;
  created_at: string;
};

export type Assignment = {
  id: string;
  platform_id: string;
  user_id: string;
  schedule: Schedule;
  is_active: boolean;
  created_at: string;
};

export type PostingLog = {
  id: string;
  org_id: string;
  user_id: string;
  platform_id: string;
  scheduled_date: string; // "yyyy-MM-dd"
  status: LogStatus;
  posted_at: string | null;
  post_url: string | null;
  note: string | null;
  marked_late: boolean;
  created_at: string;
};

export type PushSubscriptionRow = {
  id: string;
  user_id: string;
  endpoint: string;
  p256dh: string;
  auth: string;
  user_agent: string | null;
  created_at: string;
};

export type NotificationRow = {
  id: string;
  user_id: string;
  type: NotificationType;
  payload: { title?: string; body?: string; url?: string };
  ref_date: string;
  sent_at: string;
  delivered: boolean;
  read_at: string | null;
};

/** posting_log joined with its platform, as most screens consume it. */
export type LogWithPlatform = PostingLog & { platform: Platform };
