import type { Metadata } from "next";

/**
 * Single source of truth for everything Google needs to identify Umvix as one
 * consistent entity: naming, description, contact details, offices, and the
 * official profiles referenced from `sameAs` in the Organization JSON-LD.
 *
 * Keep the values here identical to the ones used on LinkedIn, Instagram, and
 * any other official Umvix profile — matching name/logo/description/URL across
 * properties is what lets search engines link them to the same company.
 */
export const siteConfig = {
  name: "Umvix",
  /** Used for `legalName` in structured data; update if the registered name differs. */
  legalName: "Umvix",
  url: "https://www.umvix.com",
  /** One-line answer to "what is Umvix?" — reused in meta tags and JSON-LD. */
  description:
    "Umvix is a software development agency building web platforms, mobile apps, AI chatbots, and automation for founders and growing teams worldwide.",
  /** Longer entity description for the Organization schema and About page. */
  longDescription:
    "Umvix is a software development agency that designs and ships web platforms, mobile apps, AI chatbots, custom dashboards, SaaS products, and AI automation workflows. We work with founders, startups, and growing teams across the US, Europe, and the Middle East.",
  email: "info@umvix.com",
  phone: "+92-316 5310133",
  /** E.164 form, required for structured data. */
  phoneE164: "+923165310133",
  logo: "/icons/logo-main.png",
  /** Generated by `npm run og` (scripts/generate-og-image.mjs). */
  ogImage: "/og.png",
  offices: [
    {
      label: "Germany",
      streetAddress: "Morgenbreede 29",
      addressLocality: "Bielefeld",
      postalCode: "33615",
      addressCountry: "DE",
    },
    {
      label: "Pakistan",
      streetAddress: "Blue Area",
      addressLocality: "Islamabad",
      addressCountry: "PK",
    },
  ],
  /**
   * Official Umvix profiles. These feed BOTH the footer icons and the
   * `sameAs` array in the Organization JSON-LD — entries with an empty `href`
   * are skipped in both places, so nothing renders until a real URL is added.
   *
   * Only add profiles that are genuinely owned and branded as Umvix, with the
   * same name, logo, and description as this site. A wrong or unclaimed URL
   * here actively confuses Google's entity matching.
   */
  socialProfiles: [
    { label: "LinkedIn", key: "linkedin", href: "https://www.linkedin.com/company/umvix/" },
    { label: "Instagram", key: "instagram", href: "https://www.instagram.com/umvix.sol/" },
    { label: "X", key: "x", href: "https://x.com/UmVix" },
    { label: "GitHub", key: "github", href: "https://github.com/UmVix" },
    { label: "Medium", key: "medium", href: "" },
  ] as { label: string; key: SocialKey; href: string }[],
};

export type SocialKey = "linkedin" | "instagram" | "x" | "github" | "medium";

/** Official profile URLs that are actually configured. */
export function getActiveProfiles() {
  return siteConfig.socialProfiles.filter((profile) => profile.href.length > 0);
}

export function absoluteUrl(path = ""): string {
  return `${siteConfig.url}${path}`;
}

export function createMetadata({
  title,
  fullTitle,
  description,
  path = "",
}: {
  /** Page name; rendered as "<title> | Umvix". */
  title?: string;
  /** Complete title, used verbatim without the "| Umvix" suffix. */
  fullTitle?: string;
  description?: string;
  path?: string;
}): Metadata {
  const pageTitle =
    fullTitle ?? (title ? `${title} | ${siteConfig.name}` : siteConfig.name);
  const pageDescription = description ?? siteConfig.description;
  const canonical = absoluteUrl(path);

  return {
    metadataBase: new URL(siteConfig.url),
    title: pageTitle,
    description: pageDescription,
    applicationName: siteConfig.name,
    alternates: {
      canonical,
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
    icons: {
      // Google only considers square favicons whose size is a multiple of 48px,
      // and fetches /favicon.ico at the root regardless of these tags.
      icon: [
        { url: "/favicon.ico", sizes: "48x48", type: "image/x-icon" },
        { url: "/icons/favicon-48.png", sizes: "48x48", type: "image/png" },
        { url: "/icons/favicon-96.png", sizes: "96x96", type: "image/png" },
        { url: "/icons/favicon-144.png", sizes: "144x144", type: "image/png" },
        { url: "/icons/favicon-192.png", sizes: "192x192", type: "image/png" },
      ],
      shortcut: [{ url: "/favicon.ico" }],
      apple: [
        {
          url: "/icons/apple-touch-icon.png",
          sizes: "180x180",
          type: "image/png",
        },
      ],
    },
    openGraph: {
      title: pageTitle,
      description: pageDescription,
      url: canonical,
      siteName: siteConfig.name,
      locale: "en_US",
      type: "website",
      images: [
        {
          url: siteConfig.ogImage,
          width: 1200,
          height: 630,
          alt: `${siteConfig.name} — Web, Mobile App & AI Development Agency`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: pageTitle,
      description: pageDescription,
      images: [siteConfig.ogImage],
    },
  };
}
